AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
    - "benchmarks/**/*"
    - "Rakefile"

# Rantly's property_of { ... }.check(N) API requires chaining blocks.
Style/MultilineBlockChain:
  Exclude:
    - "spec/**/properties/**/*"

Metrics/MethodLength:
  Exclude:
    - "ext/**/*"
    - "benchmarks/**/*"

Metrics/AbcSize:
  Exclude:
    - "benchmarks/**/*"
